### ISSUE TITLE
documentation?

### ISSUE THREAD

**Issue by pmdy** [qikkDB/qikkdb-community#2]
qikk.ly is down. is it possible to store the docs in github instead?

**Comment by ms-martin** [comment]
Hi @pmdy. 

Sorry for a long response time. We had some issue exporting the existing documentation from Gitbook because the company Instarea which funded this project is currently in hiatus thanks to the ongoing pandemic and certain credentials were hard to recover :) . Since Gitbook doesn't offer export option other than .pdf we had to use this format. The documentation can be found in doc/ directory in the root of this repository. Hope this helps :)

If you wish to somehow modify the documentation please use https://pdf2md.morethan.io/ (which works pretty well, except some lists and listings glitches) or similar conversion tool into Markdown and feel free to submit PR with the result.

Best regards,
qikkDB team
